## Listas
#### 0. ¿Qué es una lista?
  
Son objetos que nos permiten almacenar "otros objetos" de "clases diferentes" en una "misma estructura" (lista).
En R una lista es un objeto constituido por una colección de objetos conocidos como componentes.
La principal ventaja de las listas es que las "columnas" no tienen que tener el mismo tamaño, como en las matrices y data frames.


#### 1. Creación de listas en R

1.1. Función list()

Es una función genérica que intenta forzar su argumento a una lista. 
Para las funciones, esto devuelve la concatenación de la lista de argumentos formales y el cuerpo de la función.

  
Vamos a crear una lista un poco más sencilla y sin especificar los nombres de los objetos que la componen.

In [5]:
lista01 <- list(1:10, c("A","B","C"))               # Creamos una nueva lista sin especificar nombres.
lista01                                             # Solicitamos que nos devuelva los elementos de toda la lista.

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
[1] "A" "B" "C"

In [6]:
# Ahora, crearemos una lista especificando el nombre de las columnas de la lista.
# En este caso, debemos especificar cada uno de los elementos que la componen.
  
lista02 <- list(uno = 1, dos = c(1:6), tres = rep(1,3))  # Creamos la lista
names(lista02)
is.list(lista02)

[1] "uno"  "dos"  "tres"

[1] TRUE

In [ ]:
# Vemos que los elementos de la lista, a los que llamamos *uno*, *dos* y *tres*, tienen tamaños diferentes.
# La unica forma de almacenarlos en un mismo objeto es mediante una lista.
# Función is.list(): devuelve TRUE si y solo si su argumento es una lista. 

#### 1.2. Función as.list()

In [7]:
# Creamos una matriz
matriz01 <- matrix(c(1,3,5,7,9,8,6,4,2), 3, 3)
matriz01

[,1] [,2] [,3]
[1,] 1    7    6   
[2,] 3    9    4   
[3,] 5    8    2

In [8]:
# Forzamos a que la matrix sea una lista
lista03 <- as.list(matriz01)
lista03
class(lista03)
names(lista03)

[[1]]
[1] 1

[[2]]
[1] 3

[[3]]
[1] 5

[[4]]
[1] 7

[[5]]
[1] 9

[[6]]
[1] 8

[[7]]
[1] 6

[[8]]
[1] 4

[[9]]
[1] 2

[1] "list"

NULL

In [9]:
# OBS: podemos observar las diferentes clases de los elementos que componen la lista.

class(lista02)
class(lista02$uno)
class(lista02$dos)
class(lista02$tres)

[1] "list"

[1] "numeric"

[1] "integer"

[1] "numeric"

####  2. Acceso a los elementos con nombre de una lista

In [10]:
# Acceso a los elementos con nombre de una lista
  
lista02$uno         # Accedemos al primer elemento de la lista01, llamado "uno".
lista02$dos         # Accedemos al segundo elemento de la lista01, llamado "dos".
lista02$tres        # Accedemos al tercer elemento de la lista01, llamado "tres".

[1] 1

[1] 1 2 3 4 5 6

[1] 1 1 1

In [11]:
# Acceso a los elementos sin nombre de una lista
  
lista01[[1]]    # Accedemos al primer elemento de la "lista01".
lista01[[2]]    # Accedemos al segundo elemento de la "lista01".

lista03[[1]]
lista03[[2]]
lista03[[3]]
lista03[[4]]  
lista03[[5]]
lista03[[6]]
lista03[[7]]
lista03[[8]]
lista03[[9]]    # Esto es así, pues originalmente este objeto fue creado a partir de una matriz.

[1]  1  2  3  4  5  6  7  8  9 10

[1] "A" "B" "C"

[1] 1

[1] 3

[1] 5

[1] 7

[1] 9

[1] 8

[1] 6

[1] 4

[1] 2

#### 3. Añadir nuevos elementos a una lista

In [12]:
lista02$cuatro <- c("lunes","martes","miercoles","jueves","viernes")
lista02$cinco <- matrix(1:9, 3, 3)
lista02

$uno
[1] 1

$dos
[1] 1 2 3 4 5 6

$tres
[1] 1 1 1

$cuatro
[1] "lunes"     "martes"    "miercoles" "jueves"    "viernes"  

$cinco
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

In [13]:
lista02$seis <- data.frame(a = c(1,2,3), b = c(FALSE, TRUE, TRUE), c = c("Alpha", "beta","theta"))
lista02

$uno
[1] 1

$dos
[1] 1 2 3 4 5 6

$tres
[1] 1 1 1

$cuatro
[1] "lunes"     "martes"    "miercoles" "jueves"    "viernes"  

$cinco
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$seis
  a     b     c
1 1 FALSE Alpha
2 2  TRUE  beta
3 3  TRUE theta

In [14]:
class(lista02$cuatro)
class(lista02$cinco)
class(lista02$seis)

[1] "character"

[1] "matrix"

[1] "data.frame"

In [15]:
# También podemos modificar o sustituir un componente de una lista
  
lista02[3] <- list(c(rep(1,4)))

lista02

$uno
[1] 1

$dos
[1] 1 2 3 4 5 6

$tres
[1] 1 1 1 1

$cuatro
[1] "lunes"     "martes"    "miercoles" "jueves"    "viernes"  

$cinco
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$seis
  a     b     c
1 1 FALSE Alpha
2 2  TRUE  beta
3 3  TRUE theta